import React, {
  useEffect,
  useMemo,
  useState,
} from "react";
import {
  CheckCircle2,
  ChevronDown,
  CircleAlert,
  Clock3,
  Eye,
  FileText,
  Download,
  Plus,
  RefreshCw,
  Search,
  Send,
  Trash2,
  Truck,
  X,
  XCircle,
} from "lucide-react";
import "./traffic.css";
/* =========================================================
   API
========================================================= */
const API_BASE_URL = (
  import.meta.env.VITE_API_URL ||
  "http://localhost:5000"
).replace(/\/$/, "");
const TRIP_API_URL =
  `${API_BASE_URL}/api/triporders`;
/* =========================================================
   HELPERS
========================================================= */
const extractTripList = (payload) => {
  if (Array.isArray(payload)) {
    return payload;
  }
  if (Array.isArray(payload?.data)) {
    return payload.data;
  }
  if (Array.isArray(payload?.trips)) {
    return payload.trips;
  }
  if (Array.isArray(payload?.orders)) {
    return payload.orders;
  }
  return [];
};
const extractTrip = (payload) =>
  payload?.data ||
  payload?.trip ||
  payload?.order ||
  payload;
const formatDate = (value) => {
  if (!value) {
    return "—";
  }
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return "—";
  }
  return new Intl.DateTimeFormat(
    "en-IN",
    {
      day: "2-digit",
      month: "short",
      year: "numeric",
    }
  ).format(date);
};
const formatAmount = (value) => {
  if (
    value === "" ||
    value === null ||
    value === undefined
  ) {
    return "—";
  }
  const number = Number(value);
  if (Number.isNaN(number)) {
    return "—";
  }
  return new Intl.NumberFormat(
    "en-IN",
    {
      style: "currency",
      currency: "INR",
      maximumFractionDigits: 0,
    }
  ).format(number);
};
/* =========================================================
   TEMPORARY QUOTATION FORM
   quotationId is generated by backend.
========================================================= */
const createQuotationForm = () => ({
  localId:
    `LOCAL-${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}`,
  transporter: "",
  quantity: 1,
  amount: "",
  allocatedBy: "",
  remarks: "",
  isNew: true,
});
/* =========================================================
   REQUIREMENTS
========================================================= */
const getVehicleRequirements = (order) =>
  Array.isArray(order?.vehicleRequirements)
    ? order.vehicleRequirements
    : [];
const getRequirementQuantity = (
  requirement
) => {
  const value =
    Number(requirement?.quantity);
  return Number.isFinite(value)
    ? value
    : 0;
};
const getTotalVehicleQuantity = (
  order
) =>
  getVehicleRequirements(order)
    .reduce(
      (total, requirement) =>
        total +
        getRequirementQuantity(
          requirement
        ),
      0
    );
/* =========================================================
   QUOTATIONS
========================================================= */
const getTrafficQuotations = (order) =>
  Array.isArray(order?.trafficQuotations)
    ? order.trafficQuotations
    : [];
const getRequirementQuotations = (
  order,
  requirementId
) =>
  getTrafficQuotations(order).filter(
    (quotation) =>
      quotation.requirementId ===
      requirementId
  );
/* =========================================================
   CONFIRMATIONS
========================================================= */
const getVehicleConfirmations = (
  order
) =>
  Array.isArray(order?.vehicleConfirmations)
    ? order.vehicleConfirmations
    : [];
const getTransportReplacementRequests = (order) =>
  Array.isArray(order?.transportReplacementRequests)
    ? order.transportReplacementRequests
    : [];
const getPendingTransportReplacementForRequirement = (
  order,
  requirementId
) =>
  getTransportReplacementRequests(order).find(
    (item) =>
      String(item?.requirementId || "") ===
      String(requirementId || "") &&
      String(item?.status || "").trim().toLowerCase() ===
      "pending"
  );
const hasPendingTransportReplacement = (order) =>
  getTransportReplacementRequests(order).some(
    (item) =>
      String(item?.status || "").trim().toLowerCase() ===
      "pending"
  );
const getPendingTransportReplacement = (
  order,
  confirmationId
) =>
  getTransportReplacementRequests(order).find(
    (item) =>
      item.currentConfirmationId === confirmationId &&
      item.status === "Pending"
  );
const createTransportReplacementForm = (
  requirement,
  confirmation,
  quotation
) => ({
  requirementId: requirement?.requirementId || "",
  currentConfirmationId: confirmation?.confirmationId || "",
  currentQuotationId: quotation?.quotationId || "",
  currentTransporter: quotation?.transporter || "",
  currentAmount: quotation?.amount ?? "",
  proposedTransporter: "",
  proposedAmount: quotation?.amount ?? "",
  quantity: Math.max(1, Number(quotation?.quantity) || 1),
  reason: "",
  remarks: "",
  requestedBy: "",
});
/* =========================================================
   ACTUAL / CURRENT VEHICLES
========================================================= */
const getAllocatedVehicles = (order) =>
  Array.isArray(order?.allocatedVehicles)
    ? order.allocatedVehicles
    : [];
const getAllocatedVehiclesForRequirement = (
  order,
  requirementId
) =>
  getAllocatedVehicles(order).filter(
    (vehicle) =>
      String(vehicle?.requirementId || "") ===
      String(requirementId || "")
  );
const createTrafficVehicleForm = () => ({
  vehicleNumber: "",
  driverName: "",
  driverContactNumber: "",
});
const createTrafficReplacementForm = (vehicle) => ({
  allocationId: vehicle?.allocationId || "",
  oldVehicleNumber: vehicle?.vehicleNumber || "",
  newVehicleNumber: "",
  driverName: vehicle?.driver?.name || "",
  driverContactNumber: vehicle?.driver?.contactNumber || "",
  reason: "",
  remarks: "",
  replacedBy: "",
});
const getApprovedConfirmationsForRequirement = (
  order,
  requirementId
) =>
  getVehicleConfirmations(order).filter(
    (confirmation) =>
      confirmation.requirementId === requirementId &&
      String(confirmation.status || "").trim().toLowerCase() ===
      "approved"
  );
const getRequirementConfirmation = (
  order,
  requirementId
) => {
  const confirmations =
    getVehicleConfirmations(order)
      .filter(
        (confirmation) =>
          confirmation.requirementId ===
          requirementId
      );
  if (!confirmations.length) {
    return null;
  }
  return (
    confirmations.find(
      (confirmation) =>
        confirmation.status ===
        "Approved"
    ) ||
    confirmations.find(
      (confirmation) =>
        confirmation.status ===
        "Rejected"
    ) ||
    confirmations[
    confirmations.length - 1
    ]
  );
};
const getApprovedQuantityForRequirement = (
  order,
  requirementId
) => {
  const quotations =
    getRequirementQuotations(
      order,
      requirementId
    );
  const confirmations =
    getVehicleConfirmations(order)
      .filter(
        (confirmation) =>
          confirmation.requirementId === requirementId &&
          confirmation.status === "Approved"
      );
  return confirmations.reduce(
    (total, confirmation) => {
      const quotation =
        quotations.find(
          (item) =>
            item.quotationId ===
            confirmation.quotationId
        );
      return (
        total +
        Math.max(
          1,
          Number(quotation?.quantity) || 1
        )
      );
    },
    0
  );
};
/* =========================================================
   REQUIREMENT STATUS
   Quotation Pending:
   No quotations exist.
   Approval Pending:
   Traffic quotation exists but management has not
   approved/rejected it yet.
   Approved:
   Management approved a quotation.
   Rejected:
   Management rejected the quotation.
========================================================= */
const getRequirementStatus = (
  order,
  requirementId
) => {
  const pendingReplacement =
    getPendingTransportReplacementForRequirement(
      order,
      requirementId
    );
  if (pendingReplacement) {
    return "Replacement Pending";
  }
  const quotations =
    getRequirementQuotations(
      order,
      requirementId
    );
  if (!quotations.length) {
    return "Quotation Pending";
  }
  const requirement =
    getVehicleRequirements(order).find(
      (item) =>
        item.requirementId === requirementId
    );
  const requiredQuantity =
    Math.max(
      1,
      Number(requirement?.quantity) || 1
    );
  const approvedQuantity =
    getApprovedQuantityForRequirement(
      order,
      requirementId
    );
  if (approvedQuantity >= requiredQuantity) {
    return "Approved";
  }
  const confirmations =
    getVehicleConfirmations(order).filter(
      (confirmation) =>
        confirmation.requirementId === requirementId
    );
  if (
    approvedQuantity === 0 &&
    confirmations.length > 0 &&
    confirmations.every(
      (confirmation) =>
        confirmation.status === "Rejected"
    )
  ) {
    return "Rejected";
  }
  return "Approval Pending";
};
const getOrderQuotationStatus = (
  order
) => {
  const requirements =
    getVehicleRequirements(order);
  if (!requirements.length) {
    return "Quotation Pending";
  }
  const statuses =
    requirements.map(
      (requirement) =>
        getRequirementStatus(
          order,
          requirement.requirementId
        )
    );
  if (
    statuses.some(
      (status) =>
        status === "Replacement Pending"
    )
  ) {
    return "Replacement Pending";
  }
  if (
    statuses.every(
      (status) =>
        status === "Approved"
    )
  ) {
    return "Approved";
  }
  if (
    statuses.some(
      (status) =>
        status === "Rejected"
    )
  ) {
    return "Rejected";
  }
  if (
    statuses.some(
      (status) =>
        status === "Quotation Pending"
    )
  ) {
    return "Quotation Pending";
  }
  return "Approval Pending";
};
/* =========================================================
   STATUS UI
========================================================= */
const getStatusClass = (
  status
) => {
  switch (status) {
    case "Approved":
      return "selected";
    case "Rejected":
      return "rejected";
    case "Approval Pending":
    case "Replacement Pending":
      return "waiting";
    default:
      return "pending";
  }
};
const StatusIcon = ({
  status,
}) => {
  switch (status) {
    case "Approved":
      return (
        <CheckCircle2
          size={13}
        />
      );
    case "Rejected":
      return (
        <XCircle
          size={13}
        />
      );
    case "Approval Pending":
    case "Replacement Pending":
      return (
        <Clock3
          size={13}
        />
      );
    default:
      return (
        <Clock3
          size={13}
        />
      );
  }
};
/* =========================================================
   ROUTE / SITE
========================================================= */
const getRouteText = (order) => {
  if (
    order?.movementType ===
    "Intercarting"
  ) {
    return (
      order.siteLocation ||
      `${order.origin || "—"} → ${order.destination || "—"
      }`
    );
  }
  return `${order?.origin || "—"} → ${order?.destination || "—"
    }`;
};
/* =========================================================
   CRANE MOVEMENT
========================================================= */
const isCraneMovement = (order) =>
  String(order?.movementType || "")
    .trim()
    .toLowerCase() === "crane";
const getCraneDocumentUrl = (
  order,
  disposition = "inline"
) => {
  if (!order?._id) {
    return "";
  }
  return `${TRIP_API_URL}/${order._id}/crane-document/file?disposition=${disposition}`;
};
/* =========================================================
   TRAFFIC
========================================================= */
const Traffic = () => {
  const [
    orders,
    setOrders,
  ] = useState([]);
  const [
    loading,
    setLoading,
  ] = useState(true);
  const [
    error,
    setError,
  ] = useState("");
  const [
    search,
    setSearch,
  ] = useState("");
  const [
    statusFilter,
    setStatusFilter,
  ] = useState("All");
  const [
    selectedOrder,
    setSelectedOrder,
  ] = useState(null);
  /*
   * Each item:
   *
   * {
   *   ...requirement,
   *   quotations: []
   * }
   */
  const [
    requirementForms,
    setRequirementForms,
  ] = useState([]);
  const [
    saving,
    setSaving,
  ] = useState(false);
  const [
    message,
    setMessage,
  ] = useState("");
  /* =========================================================
     TRAFFIC ACTUAL VEHICLE / REPLACEMENT
  ========================================================= */
  const [
    trafficVehicleForms,
    setTrafficVehicleForms,
  ] = useState({});
  const [
    trafficReplacementForm,
    setTrafficReplacementForm,
  ] = useState(null);
  const [
    transportReplacementForm,
    setTransportReplacementForm,
  ] = useState(null);
  /* =========================================================
     TRANSPORT REPLACEMENT REQUEST
  ========================================================= */
  const openTransportReplacement = (
    requirement,
    confirmation,
    quotation
  ) => {
    if (!requirement || !confirmation || !quotation) return;
    setTransportReplacementForm(
      createTransportReplacementForm(
        requirement,
        confirmation,
        quotation
      )
    );
  };
  const closeTransportReplacement = () => {
    if (!saving) {
      setTransportReplacementForm(null);
    }
  };
  const handleTransportReplacementChange = (
    field,
    value
  ) => {
    setTransportReplacementForm((previous) =>
      previous
        ? {
          ...previous,
          [field]: value,
        }
        : previous
    );
  };
  const handleTransportReplacementRequest = async () => {
    if (!selectedOrder?._id || !transportReplacementForm) {
      return;
    }
    if (!String(transportReplacementForm.proposedTransporter || "").trim()) {
      showToast("New transporter name is required.", "warning");
      return;
    }
    if (
      transportReplacementForm.proposedAmount === "" ||
      Number(transportReplacementForm.proposedAmount) < 0
    ) {
      showToast("Valid proposed amount is required.", "warning");
      return;
    }
    if (!String(transportReplacementForm.reason || "").trim()) {
      showToast("Replacement reason is required.", "warning");
      return;
    }
    try {
      setSaving(true);
      setMessage("");
      const response = await fetch(
        `${TRIP_API_URL}/${selectedOrder._id}/transport-replacement-requests`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Accept: "application/json",
          },
          body: JSON.stringify({
            requirementId: transportReplacementForm.requirementId,
            currentConfirmationId:
              transportReplacementForm.currentConfirmationId,
            currentQuotationId:
              transportReplacementForm.currentQuotationId,
            proposedTransporter:
              String(
                transportReplacementForm.proposedTransporter || ""
              ).trim(),
            proposedAmount:
              Number(transportReplacementForm.proposedAmount),
            quantity:
              Math.max(
                1,
                Number(transportReplacementForm.quantity) || 1
              ),
            reason:
              String(transportReplacementForm.reason || "").trim(),
            remarks:
              String(transportReplacementForm.remarks || "").trim(),
            requestedBy:
              String(
                transportReplacementForm.requestedBy || "Traffic Team"
              ).trim(),
          }),
        }
      );
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(
          payload?.message ||
          "Unable to request transport replacement."
        );
      }
      const updatedOrder = extractTrip(payload);
      if (updatedOrder?._id) {
        setSelectedOrder(updatedOrder);
        setOrders((previous) =>
          previous.map((order) =>
            order._id === updatedOrder._id
              ? updatedOrder
              : order
          )
        );
      }
      setTransportReplacementForm(null);
      setMessage(
        "Transport replacement request sent to Approval Management."
      );
      showToast(
        "Transport replacement sent for approval.",
        "success"
      );
    } catch (requestError) {
      console.error(
        "Transport replacement request error:",
        requestError
      );
      showToast(
        requestError.message ||
        "Unable to request transport replacement.",
        "error"
      );
    } finally {
      setSaving(false);
    }
  };
  /* =========================================================
     COMPACT BOTTOM-RIGHT TOAST
  ========================================================= */
  const [toast, setToast] = useState(null);
  const showToast = (toastMessage, type = "success") => {
    setToast({
      message: toastMessage,
      type,
      id: Date.now(),
    });
  };
  useEffect(() => {
    if (!toast) return undefined;
    const timer = window.setTimeout(() => {
      setToast(null);
    }, 2800);
    return () => window.clearTimeout(timer);
  }, [toast]);
  /* =========================================================
     BUILD REQUIREMENT FORMS
  ========================================================= */
  const loadRequirementForms = (
    order
  ) => {
    const requirements =
      getVehicleRequirements(order);
    const forms =
      requirements.map(
        (requirement) => {
          const existing =
            getRequirementQuotations(
              order,
              requirement.requirementId
            ).map(
              (quotation) => ({
                ...quotation,
                quantity:
                  Math.max(
                    1,
                    Number(quotation.quantity) || 1
                  ),
                allocatedBy: quotation.quotedBy || "",
                isNew: false,
              })
            );
          const requiredQuantity =
            Math.max(
              1,
              Math.floor(
                getRequirementQuantity(requirement)
              )
            );
          return {
            ...requirement,
            quotations:
              existing.length
                ? existing
                : [
                  {
                    ...createQuotationForm(),
                    quantity: 1,
                  },
                ],
          };
        }
      );
    setRequirementForms(forms);
  };
  /* =========================================================
     FETCH ORDERS
  ========================================================= */
  const fetchOrders =
    async () => {
      try {
        setLoading(true);
        setError("");
        const response =
          await fetch(
            TRIP_API_URL
          );
        const result =
          await response
            .json()
            .catch(
              () => ({})
            );
        if (!response.ok) {
          throw new Error(
            result.message ||
            "Unable to load traffic requests."
          );
        }
        const allOrders =
          extractTripList(result);
        /*
         * Key Account creates the order with:
         *
         * stage = Vehicle Requirement
         *
         * Traffic should receive orders having
         * actual vehicleRequirements.
         *
         * We do NOT depend on old approvalStatus.
         */
        const trafficOrders =
          allOrders.filter(
            (order) =>
              order.orderApproval?.status ===
              "Approved" &&
              Array.isArray(
                order.vehicleRequirements
              ) &&
              order.vehicleRequirements
                .length > 0
          );
        setOrders(
          trafficOrders
        );
        if (selectedOrder?._id) {
          const fresh =
            trafficOrders.find(
              (order) =>
                order._id ===
                selectedOrder._id
            );
          if (fresh) {
            setSelectedOrder(
              fresh
            );
            loadRequirementForms(
              fresh
            );
          }
        }
      } catch (err) {
        console.error(
          "Traffic Fetch Error:",
          err
        );
        setError(
          err.message ||
          "Unable to load requests."
        );
      } finally {
        setLoading(false);
      }
    };
  useEffect(() => {
    fetchOrders();
  }, []);
  /* =========================================================
     OPEN ORDER
  ========================================================= */
  const handleOpenOrder = (
    order
  ) => {
    setSelectedOrder(order);
    loadRequirementForms(
      order
    );
    setMessage("");
    document.body.style.overflow =
      "hidden";
  };
  /* =========================================================
     CLOSE ORDER
  ========================================================= */
  const handleCloseOrder =
    () => {
      setSelectedOrder(null);
      setRequirementForms([]);
      setMessage("");
      document.body.style.overflow =
        "";
    };
  /* =========================================================
     CLEANUP BODY SCROLL
  ========================================================= */
  useEffect(() => {
    return () => {
      document.body.style.overflow =
        "";
    };
  }, []);
  /* =========================================================
     TRAFFIC ACTUAL VEHICLE ALLOCATION
  ========================================================= */
  const handleTrafficVehicleChange = (
    requirementId,
    field,
    value
  ) => {
    setTrafficVehicleForms((previous) => ({
      ...previous,
      [requirementId]: {
        ...(previous[requirementId] || createTrafficVehicleForm()),
        [field]: value,
      },
    }));
  };
  const handleTrafficAllocateVehicle = async (
    requirement,
    confirmation,
    quotation
  ) => {
    if (!selectedOrder?._id) return;
    const requirementId = requirement.requirementId;
    const form =
      trafficVehicleForms[requirementId] ||
      createTrafficVehicleForm();
    const vehicleNumber = String(
      form.vehicleNumber || ""
    )
      .trim()
      .toUpperCase();
    if (!vehicleNumber) {
      showToast("Vehicle number is required.", "error");
      return;
    }
    try {
      setSaving(true);
      const response = await fetch(
        `${TRIP_API_URL}/${selectedOrder._id}/traffic-allocated-vehicles`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            requirementId,
            confirmationId: confirmation.confirmationId,
            quotationId: quotation.quotationId,
            vehicleNumber,
            driver: {
              name: String(form.driverName || "").trim(),
              contactNumber: String(
                form.driverContactNumber || ""
              ).trim(),
            },
          }),
        }
      );
      const result = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(
          result?.message ||
          "Unable to allocate Traffic vehicle."
        );
      }
      setTrafficVehicleForms((previous) => ({
        ...previous,
        [requirementId]: createTrafficVehicleForm(),
      }));
      showToast(
        `${vehicleNumber} allocated successfully.`,
        "success"
      );
      await fetchOrders();
    } catch (err) {
      showToast(
        err.message || "Unable to allocate Traffic vehicle.",
        "error"
      );
    } finally {
      setSaving(false);
    }
  };
  const openTrafficReplacement = (vehicle) => {
    setTrafficReplacementForm(
      createTrafficReplacementForm(vehicle)
    );
  };
  const closeTrafficReplacement = () => {
    if (!saving) {
      setTrafficReplacementForm(null);
    }
  };
  const handleTrafficReplacementChange = (
    field,
    value
  ) => {
    setTrafficReplacementForm((previous) =>
      previous
        ? {
          ...previous,
          [field]: value,
        }
        : previous
    );
  };
  const handleTrafficReplacement = async () => {
    if (
      !selectedOrder?._id ||
      !trafficReplacementForm?.allocationId
    ) {
      return;
    }
    const newVehicleNumber = String(
      trafficReplacementForm.newVehicleNumber || ""
    )
      .trim()
      .toUpperCase();
    if (!newVehicleNumber) {
      showToast(
        "New vehicle number is required.",
        "error"
      );
      return;
    }
    if (
      !String(trafficReplacementForm.reason || "").trim()
    ) {
      showToast(
        "Replacement reason is required.",
        "error"
      );
      return;
    }
    try {
      setSaving(true);
      const response = await fetch(
        `${TRIP_API_URL}/${selectedOrder._id}/allocated-vehicles/${trafficReplacementForm.allocationId}/traffic-replacement`,
        {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            newVehicleNumber,
            driver: {
              name: String(
                trafficReplacementForm.driverName || ""
              ).trim(),
              contactNumber: String(
                trafficReplacementForm.driverContactNumber || ""
              ).trim(),
            },
            reason: String(
              trafficReplacementForm.reason || ""
            ).trim(),
            remarks: String(
              trafficReplacementForm.remarks || ""
            ).trim(),
            replacedBy: String(
              trafficReplacementForm.replacedBy || ""
            ).trim(),
          }),
        }
      );
      const result = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(
          result?.message ||
          "Unable to replace Traffic vehicle."
        );
      }
      setTrafficReplacementForm(null);
      showToast(
        `${newVehicleNumber} is now the current vehicle.`,
        "success"
      );
      await fetchOrders();
    } catch (err) {
      showToast(
        err.message || "Unable to replace Traffic vehicle.",
        "error"
      );
    } finally {
      setSaving(false);
    }
  };
  /* =========================================================
     FILTER
  ========================================================= */
  const filteredOrders =
    useMemo(() => {
      const text =
        search
          .trim()
          .toLowerCase();
      return orders.filter(
        (order) => {
          const status =
            getOrderQuotationStatus(
              order
            );
          const matchesStatus =
            statusFilter ===
            "All" ||
            status ===
            statusFilter;
          const searchable = [
            order.tripId,
            order.customer,
            order.contactPerson,
            order.contactNumber,
            order.email,
            order.assignedKam,
            order.origin,
            order.destination,
            order.siteLocation,
            order.materialType,
            order.movementType,
          ]
            .filter(Boolean)
            .join(" ")
            .toLowerCase();
          const matchesSearch =
            !text ||
            searchable.includes(
              text
            );
          return (
            matchesStatus &&
            matchesSearch
          );
        }
      );
    }, [
      orders,
      search,
      statusFilter,
    ]);
  /* =========================================================
     COUNTS
  ========================================================= */
  const counts =
    useMemo(() => {
      let pending = 0;
      let waiting = 0;
      let approved = 0;
      let rejected = 0;
      orders.forEach(
        (order) => {
          const status =
            getOrderQuotationStatus(
              order
            );
          if (
            status ===
            "Quotation Pending"
          ) {
            pending += 1;
          }
          if (
            status === "Approval Pending" ||
            status === "Replacement Pending"
          ) {
            waiting += 1;
          }
          if (
            status ===
            "Approved"
          ) {
            approved += 1;
          }
          if (
            status ===
            "Rejected"
          ) {
            rejected += 1;
          }
        }
      );
      return {
        pending,
        waiting,
        approved,
        rejected,
      };
    }, [orders]);
  /* =========================================================
     QUOTATION INPUT CHANGE
  ========================================================= */
  const handleQuotationChange = (
    requirementIndex,
    quotationIndex,
    field,
    value
  ) => {
    setRequirementForms(
      (previous) =>
        previous.map(
          (
            requirement,
            currentRequirementIndex
          ) => {
            if (
              currentRequirementIndex !==
              requirementIndex
            ) {
              return requirement;
            }
            const quotations = [
              ...(requirement.quotations ||
                []),
            ];
            quotations[
              quotationIndex
            ] = {
              ...quotations[
              quotationIndex
              ],
              [field]:
                value,
            };
            return {
              ...requirement,
              quotations,
            };
          }
        )
    );
  };
  /* =========================================================
     ADD QUOTATION FORM
  ========================================================= */
  const handleAddTransport = (
    requirementIndex
  ) => {
    setRequirementForms(
      (previous) =>
        previous.map(
          (
            requirement,
            index
          ) =>
            index ===
              requirementIndex
              ? {
                ...requirement,
                quotations: [
                  ...(requirement.quotations ||
                    []),
                  createQuotationForm(),
                ],
              }
              : requirement
        )
    );
  };
  /* =========================================================
     REMOVE UNSAVED QUOTATION
  ========================================================= */
  const handleRemoveTransport = (
    requirementIndex,
    quotationIndex
  ) => {
    setRequirementForms(
      (previous) =>
        previous.map(
          (
            requirement,
            index
          ) => {
            if (
              index !==
              requirementIndex
            ) {
              return requirement;
            }
            const quotations =
              (
                requirement.quotations ||
                []
              ).filter(
                (
                  _,
                  currentIndex
                ) =>
                  currentIndex !==
                  quotationIndex
              );
            return {
              ...requirement,
              quotations:
                quotations.length
                  ? quotations
                  : [
                    {
                      ...createQuotationForm(),
                      quantity: 1,
                    },
                  ],
            };
          }
        )
    );
  };
  /* =========================================================
     SAVE QUOTATIONS
     IMPORTANT:
     Each quotation is now posted separately to:
     POST /api/triporders/:id/quotations
     Payload:
     {
       requirementId,
       transporter,
       quantity,
       amount,
       quotedBy,
       remarks
     }
  ========================================================= */
  const handleRequestApproval =
    async () => {
      if (!selectedOrder?._id) {
        const text = "Database order ID is missing.";
        setMessage(text);
        showToast(text, "error");
        return;
      }
      if (
        !requirementForms.length
      ) {
        const text = "No vehicle requirements found.";
        setMessage(text);
        showToast(text, "warning");
        return;
      }
      const newQuotations = [];
      for (
        let requirementIndex = 0;
        requirementIndex <
        requirementForms.length;
        requirementIndex += 1
      ) {
        const requirement =
          requirementForms[
          requirementIndex
          ];
        if (
          !requirement.requirementId
        ) {
          const text = `Requirement ID is missing for ${requirement.vehicleType ||
            `requirement ${requirementIndex + 1}`
            }.`;
          setMessage(text);
          showToast(text, "error");
          return;
        }
        const forms =
          requirement.quotations ||
          [];
        const unsavedForms =
          forms.filter(
            (quotation) =>
              quotation.isNew
          );
        /*
         * Existing quotations are already
         * stored in MongoDB.
         */
        if (!unsavedForms.length) {
          continue;
        }
        for (
          let quotationIndex = 0;
          quotationIndex <
          unsavedForms.length;
          quotationIndex += 1
        ) {
          const quotation =
            unsavedForms[
            quotationIndex
            ];
          const transporter =
            String(
              quotation.transporter ||
              ""
            ).trim();
          const amount =
            Number(
              quotation.amount
            );
          const quantity =
            Math.floor(
              Number(
                quotation.quantity
              )
            );
          const allocatedBy =
            String(
              quotation.allocatedBy ||
              ""
            ).trim();
          /*
           * Completely blank temporary rows
           * can be ignored.
           */
          if (
            !transporter &&
            (
              quotation.amount === "" ||
              quotation.amount === null ||
              quotation.amount ===
              undefined
            )
          ) {
            continue;
          }
          if (
            !Number.isFinite(quantity) ||
            quantity <= 0
          ) {
            const text =
              `Enter a valid quantity for ${requirement.vehicleType ||
              `requirement ${requirementIndex + 1}`
              }.`;
            setMessage(text);
            showToast(text, "warning");
            return;
          }
          if (!transporter) {
            const text = `Enter Transport Name for ${requirement.vehicleType ||
              `requirement ${requirementIndex + 1}`
              }.`;
            setMessage(text);
            showToast(text, "warning");
            return;
          }
          if (
            !Number.isFinite(amount) ||
            amount <= 0
          ) {
            const text =
              `Enter a valid quotation amount for ${transporter}.`;
            setMessage(text);
            showToast(text, "warning");
            return;
          }
          if (!allocatedBy) {
            const text =
              `Enter Allocated By name for ${transporter}.`;
            setMessage(text);
            showToast(text, "warning");
            return;
          }
          newQuotations.push({
            requirementId:
              requirement.requirementId,
            transporter,
            quantity,
            amount,
            quotedBy: allocatedBy,
            remarks:
              String(
                quotation.remarks ||
                ""
              ).trim(),
          });
        }
      }
      if (!newQuotations.length) {
        const text =
          "Please enter at least one new transport quotation.";
        setMessage(text);
        showToast(text, "warning");
        return;
      }
      try {
        setSaving(true);
        setMessage("");
        /*
         * Backend endpoint creates one
         * trafficQuotations[] record per call.
         */
        for (
          const quotation of
          newQuotations
        ) {
          const response =
            await fetch(
              `${TRIP_API_URL}/${selectedOrder._id}/quotations`,
              {
                method: "POST",
                headers: {
                  "Content-Type":
                    "application/json",
                },
                body:
                  JSON.stringify(
                    quotation
                  ),
              }
            );
          const result =
            await response
              .json()
              .catch(
                () => ({})
              );
          if (!response.ok) {
            throw new Error(
              result.message ||
              `Unable to save quotation for ${quotation.transporter}.`
            );
          }
        }
        /*
         * Reload canonical TripOrder from DB.
         */
        const refreshResponse =
          await fetch(
            `${TRIP_API_URL}/${selectedOrder._id}`
          );
        const refreshResult =
          await refreshResponse
            .json()
            .catch(
              () => ({})
            );
        if (!refreshResponse.ok) {
          throw new Error(
            refreshResult.message ||
            "Quotations were saved, but the order could not be refreshed."
          );
        }
        const savedOrder =
          extractTrip(
            refreshResult
          );
        setSelectedOrder(
          savedOrder
        );
        setOrders(
          (previous) =>
            previous.map(
              (order) =>
                order._id ===
                  savedOrder._id
                  ? savedOrder
                  : order
            )
        );
        loadRequirementForms(
          savedOrder
        );
        const text =
          "Transport quotations submitted successfully for management approval.";
        setMessage(text);
        showToast(text, "success");
        handleCloseOrder();
      } catch (err) {
        console.error(
          "Quotation Submit Error:",
          err
        );
        const text =
          err.message ||
          "Unable to submit transport quotations.";
        setMessage(text);
        showToast(text, "error");
      } finally {
        setSaving(false);
      }
    };
  /* =========================================================
     UI
  ========================================================= */
  return (
    <div className="traffic-page">
      {toast && (
        <div
          className={`traffic-toast traffic-toast-${toast.type}`}
          role="status"
          aria-live="polite"
          key={toast.id}
        >
          <span className="traffic-toast-icon" aria-hidden="true">
            {toast.type === "success"
              ? "✓"
              : toast.type === "error"
                ? "×"
                : "!"}
          </span>
          <div className="traffic-toast-content">
            <strong>
              {toast.type === "success"
                ? "Submitted"
                : toast.type === "error"
                  ? "Error"
                  : "Required"}
            </strong>
            <span>{toast.message}</span>
          </div>
          <button
            type="button"
            className="traffic-toast-close"
            onClick={() => setToast(null)}
            aria-label="Close notification"
          >
            ×
          </button>
        </div>
      )}
      {/* =====================================================
          HEADER
      ===================================================== */}
      <header className="traffic-page-header">
        <div>
          <span className="traffic-eyebrow">
            TRAFFIC MANAGEMENT
          </span>
          <h1>
            Transport Quotations
          </h1>
          <p>
            Add transporter quotations against
            vehicle requirements for management
            confirmation.
          </p>
        </div>
        <button
          type="button"
          className="traffic-refresh-btn"
          onClick={
            fetchOrders
          }
          disabled={
            loading
          }
        >
          <RefreshCw
            size={15}
            className={
              loading
                ? "traffic-spin"
                : ""
            }
          />
          Refresh
        </button>
      </header>
      {/* =====================================================
          MESSAGE
      ===================================================== */}
      {message && (
        <div className="traffic-message">
          <span>
            {message}
          </span>
          <button
            type="button"
            onClick={() =>
              setMessage("")
            }
          >
            <X size={14} />
          </button>
        </div>
      )}
      {/* =====================================================
          SUMMARY
      ===================================================== */}
      <section className="traffic-summary">
        <article className="traffic-summary-card traffic-summary-orange">
          <div className="traffic-summary-icon pending">
            <Clock3 size={19} />
          </div>
          <div className="traffic-summary-content">
            <span>Quotation Pending</span>
            <strong>{counts.pending}</strong>
            <small>Awaiting transporter quotation</small>
          </div>
          <div className="traffic-summary-wave" aria-hidden="true">
            <svg viewBox="0 0 400 55" preserveAspectRatio="none">
              <path d="M0 31C62 8 111 52 176 33C241 14 280 5 334 22C361 30 382 31 400 25V55H0Z" fill="currentColor" />
            </svg>
          </div>
        </article>
        <article className="traffic-summary-card traffic-summary-green">
          <div className="traffic-summary-icon waiting">
            <Send size={19} />
          </div>
          <div className="traffic-summary-content">
            <span>Approval Pending</span>
            <strong>{counts.waiting}</strong>
            <small>Awaiting management approval</small>
          </div>
          <div className="traffic-summary-wave" aria-hidden="true">
            <svg viewBox="0 0 400 55" preserveAspectRatio="none">
              <path d="M0 31C62 8 111 52 176 33C241 14 280 5 334 22C361 30 382 31 400 25V55H0Z" fill="currentColor" />
            </svg>
          </div>
        </article>
        <article className="traffic-summary-card traffic-summary-blue">
          <div className="traffic-summary-icon selected">
            <CheckCircle2 size={19} />
          </div>
          <div className="traffic-summary-content">
            <span>Approved</span>
            <strong>{counts.approved}</strong>
            <small>Transporter confirmed</small>
          </div>
          <div className="traffic-summary-wave" aria-hidden="true">
            <svg viewBox="0 0 400 55" preserveAspectRatio="none">
              <path d="M0 31C62 8 111 52 176 33C241 14 280 5 334 22C361 30 382 31 400 25V55H0Z" fill="currentColor" />
            </svg>
          </div>
        </article>
        <article className="traffic-summary-card traffic-summary-teal">
          <div className="traffic-summary-icon action">
            <CircleAlert size={19} />
          </div>
          <div className="traffic-summary-content">
            <span>Rejected</span>
            <strong>{counts.rejected}</strong>
            <small>Requires quotation revision</small>
          </div>
          <div className="traffic-summary-wave" aria-hidden="true">
            <svg viewBox="0 0 400 55" preserveAspectRatio="none">
              <path d="M0 31C62 8 111 52 176 33C241 14 280 5 334 22C361 30 382 31 400 25V55H0Z" fill="currentColor" />
            </svg>
          </div>
        </article>
      </section>
      {/* =====================================================
          MAIN CARD
      ===================================================== */}
      <section className="traffic-card">
        <div className="traffic-toolbar traffic-toolbar-single-row">
          <div className="traffic-toolbar-heading">
            <div className="traffic-title-icon"><Truck size={17} /></div>
            <h2>Vehicle Requirement Requests</h2>
          </div>
          <div className="traffic-search">
            <Search
              size={15}
            />
            <input
              type="text"
              value={
                search
              }
              onChange={(
                event
              ) =>
                setSearch(
                  event.target.value
                )
              }
              placeholder="Search order, customer or route..."
            />
          </div>
          <div className="traffic-filter-select">
            <select
              value={
                statusFilter
              }
              onChange={(
                event
              ) =>
                setStatusFilter(
                  event.target.value
                )
              }
            >
              <option value="All">
                All Status
              </option>
              <option value="Quotation Pending">
                Quotation Pending
              </option>
              <option value="Approval Pending">
                Approval Pending
              </option>
              <option value="Replacement Pending">
                Replacement Pending
              </option>
              <option value="Approved">
                Approved
              </option>
              <option value="Rejected">
                Rejected
              </option>
            </select>
            <ChevronDown
              size={14}
            />
          </div>
          <span className="traffic-order-count"><strong>{filteredOrders.length}</strong> of {orders.length} orders</span>
        </div>
        {/* =================================================
            TABLE
        ================================================= */}
        <div className="traffic-table-wrap">
          <table className="traffic-order-table">
            <thead>
              <tr>
                <th>
                  S.No
                </th>
                <th>
                  Order ID
                </th>
                <th>
                  Customer
                </th>
                <th>
                  Movement
                </th>
                <th>
                  Route / Site
                </th>
                <th>
                  Vehicles
                </th>
                <th>
                  Placement Date
                </th>
                <th>
                  Quotation Status
                </th>
                <th>
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td
                    colSpan="9"
                    className="traffic-empty-row"
                  >
                    <RefreshCw
                      size={19}
                      className="traffic-spin"
                    />
                    Loading orders...
                  </td>
                </tr>
              ) : error ? (
                <tr>
                  <td
                    colSpan="9"
                    className="traffic-empty-row error"
                  >
                    {error}
                  </td>
                </tr>
              ) :
                filteredOrders.length ===
                  0 ? (
                  <tr>
                    <td
                      colSpan="9"
                      className="traffic-empty-row"
                    >
                      No vehicle requirement
                      orders found.
                    </td>
                  </tr>
                ) : (
                  filteredOrders.map(
                    (
                      order,
                      index
                    ) => {
                      const status =
                        getOrderQuotationStatus(
                          order
                        );
                      return (
                        <tr
                          key={
                            order._id ||
                            order.tripId ||
                            index
                          }
                        >
                          <td>
                            <span className="traffic-sl">
                              {index + 1}
                            </span>
                          </td>
                          <td>
                            <strong className="traffic-order-id">
                              {order.tripId ||
                                "—"}
                            </strong>
                          </td>
                          <td>
                            <strong className="traffic-client">
                              {order.customer ||
                                "—"}
                            </strong>
                            <span className="traffic-company">
                              {order.contactPerson ||
                                ""}
                            </span>
                          </td>
                          <td>
                            <span
                              className={`traffic-movement-badge ${String(order.movementType || "")
                                .trim()
                                .toLowerCase()
                                .replace(/\s+/g, "-")
                                }`}
                            >
                              {order.movementType || "—"}
                            </span>
                          </td>
                          <td>
                            <span className="traffic-route">
                              {getRouteText(
                                order
                              )}
                            </span>
                          </td>
                          <td>
                            <span className="traffic-vehicle-count">
                              <Truck
                                size={12}
                              />
                              {getTotalVehicleQuantity(
                                order
                              )}{" "}
                              NOS
                            </span>
                          </td>
                          <td>
                            {formatDate(
                              order.placementDate
                            )}
                          </td>
                          <td>
                            <span
                              className={`traffic-status ${getStatusClass(
                                status
                              )}`}
                            >
                              <StatusIcon
                                status={
                                  status
                                }
                              />
                              {status}
                            </span>
                          </td>
                          <td>
                            <button
                              type="button"
                              className="traffic-view-btn"
                              onClick={() =>
                                handleOpenOrder(
                                  order
                                )
                              }
                            >
                              <Eye
                                size={13}
                              />
                              View Order
                            </button>
                          </td>
                        </tr>
                      );
                    }
                  )
                )}
            </tbody>
          </table>
        </div>
      </section>
      {/* =====================================================
          ORDER DETAILS MODAL
      ===================================================== */}
      {selectedOrder && (
        <div
          className="traffic-modal-overlay"
          onMouseDown={(
            event
          ) => {
            if (
              event.target ===
              event.currentTarget
            ) {
              handleCloseOrder();
            }
          }}
        >
          <div className="traffic-modal">
            {/* =================================================
                MODAL HEADER
            ================================================= */}
            <div className="traffic-modal-header">
              <div className="traffic-modal-heading">
                <span>
                  TRANSPORT QUOTATION
                </span>
                <div className="traffic-modal-title-row">
                  <h2>
                    Vehicle Requirements
                  </h2>
                  <span className="traffic-modal-movement">
                    {selectedOrder.movementType || "—"}
                  </span>
                </div>
                <p>
                  {selectedOrder.tripId}
                  {" • "}
                  {selectedOrder.customer ||
                    "—"}
                </p>
              </div>
              <div className="traffic-modal-header-actions">
                <button
                  type="button"
                  className="traffic-modal-close"
                  onClick={
                    handleCloseOrder
                  }
                  aria-label="Close quotation modal"
                  disabled={
                    saving
                  }
                >
                  <X size={17} />
                </button>
              </div>
            </div>
            {/* =================================================
                ORDER INFO
            ================================================= */}
            <div className="traffic-order-overview">
              <div>
                <span>
                  Order ID
                </span>
                <strong>
                  {selectedOrder.tripId ||
                    "—"}
                </strong>
              </div>
              <div>
                <span>
                  Customer
                </span>
                <strong>
                  {selectedOrder.customer ||
                    "—"}
                </strong>
              </div>
              <div>
                <span>
                  Route
                </span>
                <strong>
                  {getRouteText(
                    selectedOrder
                  )}
                </strong>
              </div>
              <div>
                <span>
                  Placement
                </span>
                <strong>
                  {formatDate(
                    selectedOrder.placementDate
                  )}
                </strong>
              </div>
              <div>
                <span>
                  Vehicle Qty
                </span>
                <strong>
                  {getTotalVehicleQuantity(
                    selectedOrder
                  )}{" "}
                  NOS
                </strong>
              </div>
            </div>
            {/* =================================================
                REQUIREMENTS
            ================================================= */}
            <div className="traffic-modal-body">
              {isCraneMovement(selectedOrder) && (
                <section className="traffic-crane-compact">
                  <div className="traffic-crane-compact-main">
                    <div className="traffic-crane-compact-file">
                      <span className="traffic-crane-compact-icon">
                        <FileText size={16} />
                      </span>
                      <div>
                        <span className="traffic-crane-compact-label">
                          CRANE VEHICLE REQUIREMENT
                        </span>
                        <strong>
                          {selectedOrder?.craneDocument?.fileName ||
                            "No vehicle requirement document"}
                        </strong>
                      </div>
                    </div>
                    <div className="traffic-crane-compact-actions">
                      <button
                        type="button"
                        className="traffic-crane-view-btn"
                        onClick={() =>
                          window.open(
                            getCraneDocumentUrl(
                              selectedOrder,
                              "inline"
                            ),
                            "_blank",
                            "noopener,noreferrer"
                          )
                        }
                        disabled={
                          !selectedOrder?.craneDocument?.fileName
                        }
                      >
                        <Eye size={13} />
                        View
                      </button>
                      <a
                        className={`traffic-crane-download-btn ${!selectedOrder?.craneDocument?.fileName
                          ? "disabled"
                          : ""
                          }`}
                        href={
                          selectedOrder?.craneDocument?.fileName
                            ? getCraneDocumentUrl(
                              selectedOrder,
                              "attachment"
                            )
                            : undefined
                        }
                        aria-disabled={
                          !selectedOrder?.craneDocument?.fileName
                        }
                      >
                        <Download size={13} />
                        Download
                      </a>
                    </div>
                  </div>
                  <div className="traffic-crane-compact-footer">
                    <span>Vehicle Qty</span>
                    <strong>
                      {getTotalVehicleQuantity(selectedOrder) ||
                        selectedOrder?.totalVehicles ||
                        1}{" "}
                      NOS
                    </strong>
                  </div>
                </section>
              )}
              {requirementForms.map(
                (
                  requirement,
                  requirementIndex
                ) => {
                  const status =
                    getRequirementStatus(
                      selectedOrder,
                      requirement.requirementId
                    );
                  const confirmation =
                    getRequirementConfirmation(
                      selectedOrder,
                      requirement.requirementId
                    );
                  const approvedConfirmations =
                    getApprovedConfirmationsForRequirement(
                      selectedOrder,
                      requirement.requirementId
                    );
                  const approvedQuotationIds =
                    new Set(
                      approvedConfirmations
                        .map(
                          (item) =>
                            item?.quotationId
                        )
                        .filter(Boolean)
                    );
                  const approvedQuotations =
                    getRequirementQuotations(
                      selectedOrder,
                      requirement.requirementId
                    ).filter(
                      (quotation) =>
                        approvedQuotationIds.has(
                          quotation?.quotationId
                        )
                    );
                  const isApproved =
                    status ===
                    "Approved";
                  const requirementKey =
                    requirement.requirementId ||
                    requirementIndex;
                  return (
                    <section
                      className={`traffic-vehicle-card ${isCraneMovement(selectedOrder)
                        ? "traffic-crane-quotation-card"
                        : ""
                        }`}
                      key={
                        requirementKey
                      }
                    >
                      {/* =============================================
                          REQUIREMENT HEADER
                      ============================================= */}
                      <div className="traffic-vehicle-card-header">
                        <div className="traffic-vehicle-header-main">
                          <span className="traffic-vehicle-index">
                            {String(
                              requirementIndex +
                              1
                            ).padStart(
                              2,
                              "0"
                            )}
                          </span>
                          <div>
                            <h3>
                              {requirement.vehicleType ||
                                "Vehicle"}
                            </h3>
                            <p>
                              {requirement.quantity ||
                                0}{" "}
                              NOS
                              {" • "}
                              {requirement.configuration ||
                                "No Configuration"}
                              {" • "}
                              {requirement.classification ||
                                "No Classification"}
                            </p>
                          </div>
                        </div>
                        <div className="traffic-vehicle-header-actions">
                          <span
                            className={`traffic-status ${getStatusClass(
                              status
                            )}`}
                          >
                            <StatusIcon
                              status={
                                status
                              }
                            />
                            {status}
                          </span>
                          {!isApproved && (
                            <button
                              type="button"
                              className="traffic-add-btn traffic-add-btn-header"
                              onClick={() =>
                                handleAddTransport(
                                  requirementIndex
                                )
                              }
                            >
                              <Plus
                                size={13}
                              />
                              Add Transport
                            </button>
                          )}
                        </div>
                      </div>
                      {/* =============================================
                          APPROVAL RESPONSE
                      ============================================= */}
                      {approvedQuotations.length > 0 && (
                        <div className="traffic-kam-response selected">
                          <div>
                            <strong>
                              Management Response
                            </strong>
                            <p>
                              Selected{" "}
                              {approvedQuotations.map(
                                (quotation, index) => (
                                  <React.Fragment
                                    key={
                                      quotation.quotationId ||
                                      index
                                    }
                                  >
                                    <b>
                                      {quotation.transporter ||
                                        "Transporter"}
                                    </b>
                                    {" at "}
                                    <b>
                                      {formatAmount(
                                        quotation.amount
                                      )}
                                    </b>
                                    {index <
                                      approvedQuotations.length - 1 &&
                                      ", "}
                                  </React.Fragment>
                                )
                              )}
                              {approvedConfirmations?.[0]
                                ?.confirmedBy
                                ? ` by ${approvedConfirmations[0]
                                  .confirmedBy
                                }`
                                : ""}
                            </p>
                          </div>
                        </div>
                      )}
                      {status ===
                        "Rejected" && (
                          <div className="traffic-kam-response rejected">
                            <div>
                              <strong>
                                Management Response
                              </strong>
                              <p>
                                Quotation rejected.
                                {confirmation?.rejectionReason
                                  ? ` ${confirmation.rejectionReason}`
                                  : confirmation?.remarks
                                    ? ` ${confirmation.remarks}`
                                    : ""}
                              </p>
                            </div>
                          </div>
                        )}
                      {/* =============================================
                          QUOTATION TABLE
                      ============================================= */}
                      <div className="traffic-quotation-section">
                        <div className="traffic-quotation-table-wrap">
                          <table className="traffic-quotation-table">
                            <thead>
                              <tr>
                                <th>
                                  S.No
                                </th>
                                <th>
                                  Transport Name
                                </th>
                                <th>
                                  Quantity
                                </th>
                                <th>
                                  Quoted Amount
                                </th>
                                <th>
                                  Allocated By
                                </th>
                                <th>
                                  Status
                                </th>
                                {!isApproved && (
                                  <th>
                                    Action
                                  </th>
                                )}
                              </tr>
                            </thead>
                            <tbody>
                              {requirement.quotations
                                ?.length ? (
                                requirement.quotations.map(
                                  (
                                    quotation,
                                    quotationIndex
                                  ) => {
                                    const isExisting =
                                      !quotation.isNew;
                                    const selectedQuotation =
                                      isExisting &&
                                      Boolean(
                                        quotation?.quotationId
                                      ) &&
                                      approvedQuotationIds.has(
                                        quotation.quotationId
                                      );
                                    return (
                                      <tr
                                        key={
                                          quotation.quotationId ||
                                          quotation.localId ||
                                          quotationIndex
                                        }
                                        className={
                                          selectedQuotation
                                            ? "selected-option"
                                            : ""
                                        }
                                      >
                                        <td>
                                          {quotationIndex +
                                            1}
                                        </td>
                                        {/* TRANSPORTER */}
                                        <td>
                                          {isExisting ? (
                                            <strong>
                                              {quotation.transporter ||
                                                "—"}
                                            </strong>
                                          ) : (
                                            <input
                                              type="text"
                                              value={
                                                quotation.transporter ||
                                                ""
                                              }
                                              onChange={(
                                                event
                                              ) =>
                                                handleQuotationChange(
                                                  requirementIndex,
                                                  quotationIndex,
                                                  "transporter",
                                                  event.target.value
                                                )
                                              }
                                              placeholder="Enter transport name"
                                              disabled={
                                                saving
                                              }
                                            />
                                          )}
                                        </td>
                                        {/* QUANTITY */}
                                        <td>
                                          {isExisting ? (
                                            <strong className="traffic-quantity-value">
                                              {Math.max(
                                                1,
                                                Number(
                                                  quotation.quantity
                                                ) || 1
                                              )} NOS
                                            </strong>
                                          ) : (
                                            <div className="traffic-quantity-input">
                                              <input
                                                type="number"
                                                min="1"
                                                max={
                                                  getRequirementQuantity(
                                                    requirement
                                                  )
                                                }
                                                step="1"
                                                value={
                                                  quotation.quantity ??
                                                  1
                                                }
                                                onChange={(
                                                  event
                                                ) =>
                                                  handleQuotationChange(
                                                    requirementIndex,
                                                    quotationIndex,
                                                    "quantity",
                                                    event.target.value
                                                  )
                                                }
                                                disabled={
                                                  saving
                                                }
                                              />
                                              <span>
                                                NOS
                                              </span>
                                            </div>
                                          )}
                                        </td>
                                        {/* AMOUNT */}
                                        <td>
                                          {isExisting ? (
                                            <strong className="traffic-table-amount">
                                              {formatAmount(
                                                quotation.amount
                                              )}
                                            </strong>
                                          ) : (
                                            <div className="traffic-amount-input">
                                              <span>
                                                ₹
                                              </span>
                                              <input
                                                type="number"
                                                min="0"
                                                step="0.01"
                                                value={
                                                  quotation.amount ??
                                                  ""
                                                }
                                                onChange={(
                                                  event
                                                ) =>
                                                  handleQuotationChange(
                                                    requirementIndex,
                                                    quotationIndex,
                                                    "amount",
                                                    event.target.value
                                                  )
                                                }
                                                placeholder="Enter amount"
                                                disabled={
                                                  saving
                                                }
                                              />
                                            </div>
                                          )}
                                        </td>
                                        {/* ALLOCATED BY */}
                                        <td>
                                          {isExisting ? (
                                            <strong className="traffic-allocator-name">
                                              {quotation.quotedBy ||
                                                quotation.allocatedBy ||
                                                "—"}
                                            </strong>
                                          ) : (
                                            <input
                                              type="text"
                                              className="traffic-allocator-input"
                                              value={
                                                quotation.allocatedBy ||
                                                ""
                                              }
                                              onChange={(event) =>
                                                handleQuotationChange(
                                                  requirementIndex,
                                                  quotationIndex,
                                                  "allocatedBy",
                                                  event.target.value
                                                )
                                              }
                                              placeholder="Enter allocator name"
                                              disabled={saving}
                                            />
                                          )}
                                        </td>
                                        {/* STATUS */}
                                        <td>
                                          {selectedQuotation ? (
                                            <span className="traffic-option-selected">
                                              <CheckCircle2
                                                size={12}
                                              />
                                              Approved
                                            </span>
                                          ) :
                                            isExisting ? (
                                              <span className="traffic-option-pending">
                                                {status ===
                                                  "Rejected"
                                                  ? "Rejected"
                                                  : approvedQuotationIds.size > 0
                                                    ? "Not Selected"
                                                    : "Submitted"}
                                              </span>
                                            ) : (
                                              <span className="traffic-option-pending">
                                                Pending
                                              </span>
                                            )}
                                        </td>
                                        {/* DELETE */}
                                        {!isApproved && (
                                          <td>
                                            {quotation.isNew ? (
                                              <button
                                                type="button"
                                                className="traffic-delete-option"
                                                onClick={() =>
                                                  handleRemoveTransport(
                                                    requirementIndex,
                                                    quotationIndex
                                                  )
                                                }
                                                title="Remove transport option"
                                                disabled={
                                                  saving
                                                }
                                              >
                                                <Trash2
                                                  size={13}
                                                />
                                              </button>
                                            ) : (
                                              <span>
                                                —
                                              </span>
                                            )}
                                          </td>
                                        )}
                                      </tr>
                                    );
                                  }
                                )
                              ) : (
                                <tr>
                                  <td
                                    colSpan={
                                      isApproved
                                        ? 5
                                        : 6
                                    }
                                    className="traffic-no-options"
                                  >
                                    No transport
                                    quotations.
                                  </td>
                                </tr>
                              )}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      {/* =============================================
                          CONFIRMED / CURRENT TRANSPORT
                      ============================================= */}
                      {isApproved && approvedQuotations.length > 0 && (
                        <div className="traffic-current-transport-section">
                          <div className="traffic-current-transport-head">
                            <div>
                              <strong>Confirmed Transport</strong>
                              <span>
                                Approved transporter remains current until a
                                replacement request is approved.
                              </span>
                            </div>
                            <span className="traffic-current-transport-count">
                              {approvedQuotations.length} Approved
                            </span>
                          </div>
                          <div className="traffic-current-transport-list">
                            {approvedConfirmations.map((confirmation) => {
                              const quotation =
                                approvedQuotations.find(
                                  (item) =>
                                    item.quotationId ===
                                    confirmation.quotationId
                                );
                              if (!quotation) return null;
                              const pendingReplacement =
                                getPendingTransportReplacement(
                                  selectedOrder,
                                  confirmation.confirmationId
                                );
                              return (
                                <div
                                  className="traffic-current-transport-row"
                                  key={confirmation.confirmationId}
                                >
                                  <div className="traffic-current-transport-main">
                                    <Truck size={15} />
                                    <div>
                                      <strong>
                                        {quotation.transporter || "—"}
                                      </strong>
                                      <span>
                                        Current Approved Transport
                                      </span>
                                    </div>
                                  </div>
                                  <div className="traffic-current-transport-meta">
                                    <span>Quantity</span>
                                    <strong>
                                      {Math.max(
                                        1,
                                        Number(quotation.quantity) || 1
                                      )}{" "}
                                      NOS
                                    </strong>
                                  </div>
                                  <div className="traffic-current-transport-meta">
                                    <span>Approved Amount</span>
                                    <strong>
                                      {formatAmount(quotation.amount)}
                                    </strong>
                                  </div>
                                  {pendingReplacement ? (
                                    <div className="traffic-transport-pending">
                                      <Clock3 size={13} />
                                      <div>
                                        <strong>
                                          Replacement Pending
                                        </strong>
                                        <span>
                                          {pendingReplacement.proposedTransporter}
                                          {" • "}
                                          {formatAmount(
                                            pendingReplacement.proposedAmount
                                          )}
                                        </span>
                                      </div>
                                    </div>
                                  ) : (
                                    <button
                                      type="button"
                                      className="traffic-replace-transport-btn"
                                      disabled={saving}
                                      onClick={() =>
                                        openTransportReplacement(
                                          requirement,
                                          confirmation,
                                          quotation
                                        )
                                      }
                                    >
                                      <RefreshCw size={13} />
                                      Replace Transport
                                    </button>
                                  )}
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      )}
                    </section>
                  );
                }
              )}
              {/* =================================================
                  FOOTER
              ================================================= */}
              <div className="traffic-quotation-footer">
                <span>
                  Traffic Team submits transporter
                  quotations only. Management will
                  confirm the suitable transporter
                  and amount.
                </span>
                <button
                  type="button"
                  className="traffic-submit-btn"
                  disabled={saving}
                  onClick={
                    handleRequestApproval
                  }
                >
                  <Send
                    size={14}
                  />
                  {saving
                    ? "Submitting..."
                    : "Submit Quotations"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
      {transportReplacementForm && (
        <div
          className="traffic-transport-replacement-overlay"
          role="dialog"
          aria-modal="true"
          onMouseDown={(event) => {
            if (event.target === event.currentTarget) {
              closeTransportReplacement();
            }
          }}
        >
          <div className="traffic-transport-replacement-modal">
            <div className="traffic-transport-replacement-head">
              <div>
                <span>TRANSPORT REPLACEMENT REQUEST</span>
                <h3>Replace Approved Transport</h3>
                <p>
                  This request must be approved by Approval Management.
                </p>
              </div>
              <button
                type="button"
                disabled={saving}
                onClick={closeTransportReplacement}
                aria-label="Close"
              >
                <X size={17} />
              </button>
            </div>
            <div className="traffic-transport-replacement-current">
              <div>
                <span>Current Transport</span>
                <strong>
                  {transportReplacementForm.currentTransporter || "—"}
                </strong>
              </div>
              <div>
                <span>Current Amount</span>
                <strong>
                  {formatAmount(
                    transportReplacementForm.currentAmount
                  )}
                </strong>
              </div>
              <div>
                <span>Quantity</span>
                <strong>
                  {transportReplacementForm.quantity} NOS
                </strong>
              </div>
            </div>
            <div className="traffic-transport-replacement-body">
              <label>
                <span>New Transporter *</span>
                <input
                  value={
                    transportReplacementForm.proposedTransporter
                  }
                  onChange={(event) =>
                    handleTransportReplacementChange(
                      "proposedTransporter",
                      event.target.value
                    )
                  }
                  placeholder="Enter new transporter"
                  disabled={saving}
                />
              </label>
              <label>
                <span>Proposed Amount *</span>
                <input
                  type="number"
                  min="0"
                  value={
                    transportReplacementForm.proposedAmount
                  }
                  onChange={(event) =>
                    handleTransportReplacementChange(
                      "proposedAmount",
                      event.target.value
                    )
                  }
                  placeholder="Enter amount"
                  disabled={saving}
                />
              </label>
              <label>
                <span>Requested By</span>
                <input
                  value={
                    transportReplacementForm.requestedBy
                  }
                  onChange={(event) =>
                    handleTransportReplacementChange(
                      "requestedBy",
                      event.target.value
                    )
                  }
                  placeholder="Traffic team member"
                  disabled={saving}
                />
              </label>
              <label>
                <span>Reason *</span>
                <input
                  value={transportReplacementForm.reason}
                  onChange={(event) =>
                    handleTransportReplacementChange(
                      "reason",
                      event.target.value
                    )
                  }
                  placeholder="Reason for replacing transport"
                  disabled={saving}
                />
              </label>
              <label className="traffic-transport-replacement-full">
                <span>Remarks</span>
                <textarea
                  value={transportReplacementForm.remarks}
                  onChange={(event) =>
                    handleTransportReplacementChange(
                      "remarks",
                      event.target.value
                    )
                  }
                  placeholder="Optional remarks"
                  disabled={saving}
                />
              </label>
            </div>
            <div className="traffic-transport-replacement-footer">
              <button
                type="button"
                className="traffic-transport-replacement-cancel"
                disabled={saving}
                onClick={closeTransportReplacement}
              >
                Cancel
              </button>
              <button
                type="button"
                className="traffic-transport-replacement-submit"
                disabled={saving}
                onClick={handleTransportReplacementRequest}
              >
                <Send size={13} />
                {saving
                  ? "Submitting..."
                  : "Request Replacement Approval"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
export default Traffic;
